### ISSUE TITLE
无法运行命令 avoscloud

### ISSUE THREAD

**Issue by simman** [leancloud/avoscloud-code-command#111]
### >avoscloud

```
提示：您可以敲入 rs 命令并回车来重启本进程
提示：您可以使用 http://localhost:3001 测试 Cloud 函数

> node-js-getting-started@1.0.0 start /Data/NodeJs/SMSHelp
> node server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'leanengine'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Data/NodeJs/SMSHelp/server.js:2:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! node-js-getting-started@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the node-js-getting-started package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-js-getting-started
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Data/NodeJs/SMSHelp/npm-debug.log
```

### >cat npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart node-js-getting-started@1.0.0
6 info start node-js-getting-started@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info node-js-getting-started@1.0.0 Failed to exec start script
9 verbose stack Error: node-js-getting-started@1.0.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid node-js-getting-started@1.0.0
11 verbose cwd /Data/NodeJs/SMSHelp
12 error Darwin 15.0.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error node-js-getting-started@1.0.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the node-js-getting-started@1.0.0 start script 'node server.js'.
18 error This is most likely a problem with the node-js-getting-started package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls node-js-getting-started
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by sdjcw** [comment]
你好，麻烦提供下 /Data/NodeJs/SMSHelp/package.json 文件的内容。

**Comment by simman** [comment]
我在目录下运行了  `npm install` 就OK了, 谢谢！
