### ISSUE TITLE
avoscloud-code/bin/run.js 报错

### ISSUE THREAD

**Issue by guo-yu** [leancloud/avoscloud-code-command#119]
执行 deploy 操作时报错：

```
[INFO] 开始上传项目文件……
2016-01-19 18:01:18 [INFO] 命令行部署应用……
2016-01-19 18:01:18 [INFO] 获取部署包
2016-01-19 18:01:18 [INFO] 解压缩部署包
2016-01-19 18:01:18 [INFO] 运行环境: Node.js
2016-01-19 18:01:18 [INFO] 安装新的依赖
2016-01-19 18:03:37 [INFO] 备份最新的依赖包
/usr/local/lib/node_modules/avoscloud-code/bin/run.js:198
        res.logs.reverse().forEach(function(logInfo) {
                 ^
TypeError: undefined is not a function
    at util.requestCloud.success (/usr/local/lib/node_modules/avoscloud-code/bin/run.js:198:18)
    at /usr/local/lib/node_modules/avoscloud-code/node_modules/avoscloud-sdk/lib/promise.js:538:25
    at wrappedResolvedCallback (/usr/local/lib/node_modules/avoscloud-code/node_modules/avoscloud-sdk/lib/promise.js:389:38)
    at /usr/local/lib/node_modules/avoscloud-code/node_modules/avoscloud-sdk/lib/promise.js:309:24
    at Function._.each._.forEach (/usr/local/lib/node_modules/avoscloud-code/node_modules/avoscloud-sdk/node_modules/underscore/underscore.js:153:9)
    at Promise._.extend.resolve (/usr/local/lib/node_modules/avoscloud-code/node_modules/avoscloud-sdk/lib/promise.js:308:7)
    at xhr.onreadystatechange (/usr/local/lib/node_modules/avoscloud-code/lib/util.js:105:29)
    at dispatchEvent (/usr/local/lib/node_modules/avoscloud-code/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
    at setState (/usr/local/lib/node_modules/avoscloud-code/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/avoscloud-code/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:427:13)
```

**Comment by jysperm** [comment]
已解决

**Comment by guo-yu** [comment]
👍
