### ISSUE TITLE
avoscloud new 失败

### ISSUE THREAD

**Issue by callmewhy** [leancloud/avoscloud-code-command#122]
```
正在创建项目 ...
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: getaddrinfo ENOTFOUND lcinternal-cloud-code-update.avosapps.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

**Comment by jysperm** [comment]
你好，似乎这是因为你的网络无法解析 `lcinternal-cloud-code-update.avosapps.com` 这个域名，可能是临时性的网络故障，建议稍后重试。

**Comment by callmewhy** [comment]
一直这样。。包括 dns clean 也没用。。。
另外 avoscloud deploy 也没用了，无法打包。。。

```
[INFO] LeanEngine 项目根目录：/Users/why/workspace/web/lemur-wechat-spider/
[INFO] 当前应用: wechat-spider vb7dw02mnPsv8MjR03BUDCsD-*******
[INFO] 压缩项目文件……
[INFO] 生成临时文件：/var/folders/hf/050g6l2s0wj25wpw83wksvnr0000gn/T/1453691341083.zip
[INFO] 开始上传项目文件……
抱歉，上传项目文件 失败：[object Object]
查看使用帮助：avoscloud -h，或查看相关文档：https://leancloud.cn/docs/cloud_code_commandline.html
```

**Comment by jysperm** [comment]
请试一下访问这两个域名（在浏览器即可，不要开代理）：`lcinternal-cloud-code-update.avosapps.com` 和 `lcinternal-cloud-code-update.leanapp.cn`。因为部分运营商没有理由地屏蔽 av 开头的域名，所以我们正在换到 leanapp.cn 这个域名，希望再跟你核实一下情况，稍后命令行工具会发布一个使用新域名的版本。

**Comment by callmewhy** [comment]
http://lcinternal-cloud-code-update.avosapps.com/ 无法访问

http://lcinternal-cloud-code-update.leanapp.cn/ 正常

**Comment by jysperm** [comment]
avoscloud-code@0.10.0 已发布
