### ISSUE TITLE
急 avoscloud 本地终端机崩溃 

### ISSUE THREAD

**Issue by wahengchang** [leancloud/avoscloud-code-command#125]
环境ios, 在本地终端机执行 avoscloud , 在浏覧器打开http://localhost:3001/  ，或http://localhost:3000/ 都会出现错误
 
已经重新安装了 avoscloud-code , 错误讯息一样。现在我无法开发，进度落後，请尽快给出解决方法

提示：您可以敲入 rs 命令并回车来重启本进程
提示：您可以使用 http://localhost:3001 测试 Cloud 函数
undefined:1
undefined
^

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/avoscloud-code/lib/testUtilServer.js:101:17)
    at self.callback (/usr/local/lib/node_modules/avoscloud-code/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.self.clientErrorHandler (/usr/local/lib/node_modules/avoscloud-code/node_modules/request/request.js:343:10)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)

**Comment by GongT** [comment]
最新版的91行。。。body = JSON.parse(body);又没加try catch。。。

写js的意识不够啊，JSON.parse的问题不止这一处。。。

**Comment by leeyeh** [comment]
@wahengchang  请问当前项目是否有按照下面的指引正确的使用了 leanengine 中间件？https://leancloud.cn/docs/leanengine_guide-node.html#健康监测

**Comment by jysperm** [comment]
https://forum.leancloud.cn/t/avoscloud/6382

你好，这个错误发生在从 Node SDK 获取云函数信息时，请问在启动 `avoscloud` 后是否可以访问 `http://localhost:3000/1.1/functions/_ops/metadatas` ？结果是什么样的？

**Comment by leeyeh** [comment]
Resolved in https://forum.leancloud.cn/t/avoscloud/6382

**Comment by SLboat** [comment]
http://see.sl088.com/wiki/LeanCloud_%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7/%E6%9C%AC%E5%9C%B0%E8%B0%83%E8%AF%95%E5%A4%B1%E8%B4%A5 localhost可能丢了
