### ISSUE TITLE
Win7 32位 在项目根目录运行avoscloud报错

### ISSUE THREAD

**Issue by lf2941270** [leancloud/avoscloud-code-command#38]
nodejs版本为v0.10.35

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\My Documents\GitHub\afan\"D:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by lf2941270** [comment]
已自行解决：卸载了从cnpm安装的avoscloud-code，然后重新从npm安装后就好了
