### ISSUE TITLE
Cannot find module 'bytes'?

### ISSUE THREAD

**Issue by benji0818** [leancloud/avoscloud-code-command#56]
报错信息如下:
```
module.js:338
    throw err;
          ^
Error: Cannot find module 'bytes'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (/usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:365:21)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/benji/Documents/vagrant/workspace/akapollo/node_modules/express/node_modules/connect/lib/utils.js:393:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (/usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:365:21)
```

Node.js Version: 0.12.0

**Comment by aisk** [comment]
您好，这个应该是您的代码依赖的模块，请在 package.json 中指定，然后执行 npm.install 进行安装。

**Comment by benji0818** [comment]
貌似用 avoscloud-command 创造一个项目就好了 网上pull下来的就不行

**Comment by aisk** [comment]
@benji0818 pull 下来的项目依赖了那个模块，你是不是没有 npm install
