### ISSUE TITLE
升级0.7.6后，报 Error: Cannot find module 'boom' 错误

### ISSUE THREAD

**Issue by plusmancn** [leancloud/avoscloud-code-command#81]
```javascript
module.js:338
    throw err;
    ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (/usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:366:21)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/plusman/Desktop/Open/hyxNodeServer/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (/usr/local/lib/node_modules/avoscloud-code/lib/cloud_code.js:366:21)
```

**Comment by plusmancn** [comment]
是 Request 模块的问题，重装了下好了。
